- src/app/auth/register/register.component.html
> Change String to "Áreas de Atuação" on register

- src/app/pages/contracts/contract-item/payment-item/payment-item.component.html
- src/app/pages/contracts/contract-item/payment-item/payment-item.component.scss
- src/app/pages/contracts/contract-item/payment-item/payment-item.component.ts
> Change percentage text field by input field

- src/app/pages/contracts/contract-item/contract-item.component.html
- src/app/pages/contracts/contract-item/contract-item.component.ts
- src/app/pages/contracts/contract-item/payment-item/payment-item.component.html
> add remove button of payment item

- src/app/pages/contracts/contract-item/expense-item/expense-item.component.ts
> Rename expense types on expense component

- backend/src/models/platformConfig.ts
- playground.mongodb
- src/app/@theme/components/header/config/config.component.html
- src/app/pages/invoices/invoice-item/invoice-item.component.html
- src/app/pages/invoices/invoice-item/invoice-item.component.ts
Exemplo da aba complementar quando desativado todas as opções das configurações.
Lembrando que esse branch foi feito com base no branch NWS-1326 e possui algumas correções.
> Change invoice complementary tab to match config

- src/app/pages/invoices/invoice-item/invoice-item.component.ts
- src/app/pages/invoices/pdf.service.ts
[ORC---969_2022-NRT_DAD.pdf](https://github.com/nortan-ninc/plataforma/files/8497931/ORC---969_2022-NRT_DAD.pdf)
Exemplo com todas as configurações desativadas para o orçamento ORC---969_2022-NRT_DAD.
Lembrando que este branch foi feito com base no branch NWS-1327, que possui alterações importantes em relação ao NWS-1326.
> Change pdf service to match platform invoiceConfig

- src/app/pages/contracts/contract-item/management-tab/management-tab.component.html
- src/app/pages/contracts/contract-item/management-tab/management-tab.component.ts
- src/app/shared/components/charts/gantt-chart/date-manipulator.ts
- src/app/shared/components/charts/gantt-chart/gantt-chart.component.ts
- src/app/shared/components/charts/gantt-chart/gantt-renderers.ts
- src/app/shared/components/charts/gantt-chart/task-data-manipulator.ts
- src/app/shared/components/charts/gantt-chart/task-data.model.ts
> [NWS-1207][NWS-1338] Add checklist item as action's father in gantt chart

- backend/src/routes/notification.ts
- src/app/@theme/components/header/config/config-dialog/config-dialog.component.html
- src/app/@theme/components/header/config/config-dialog/config-dialog.component.ts
- src/app/@theme/components/header/header.component.html
- src/app/@theme/components/header/header.component.ts
- src/app/shared/services/notification.service.spec.ts
- src/app/shared/services/notification.service.ts
Dialogo da notificação selecionada.
> [NWS-1172][NWS-1269] Create dialog to open notification and delete on dismiss

- src/app/shared/components/charts/gantt-chart/gantt-renderers.ts
Gráfico com 5 zebras
Gráfico com 8 zebras
agora vai!! :rofl:
> [NWS-1207][NWS-1376] Fix y values in today's line on the Gantt chart

- backend/src/app.ts
- backend/src/routes/email.ts
- backend/src/routes/notification.ts
- backend/src/shared/global.ts
- backend/src/shared/util.ts
- src/app/pages/invoices/invoice-item/invoice-item.component.ts
- src/app/shared/services/notification.service.ts
Exemplo de um e-mail enviado a partir de uma notificação.
> [NWS-1172][NWS-1266] Notify in user email after notification is saved

- src/app/@theme/components/header/header.component.html
- src/app/@theme/components/header/header.component.scss
Adjust notification box and change bell icon to fill when full
> [NWS-1172][NWS-1388] Adjust notification box and change bell icon

- src/app/@theme/components/message-input/message-input.component.ts
- src/app/pages/contracts/contract-item/management-tab/management-tab.component.html
- src/app/pages/contracts/contract-item/management-tab/management-tab.component.scss
- src/app/pages/contracts/contract-item/management-tab/management-tab.component.ts
- src/app/shared/services/notification.service.ts
> [NWS-1207][NWS-1252] Notify user when mentioned in management comments

- src/app/pages/contracts/contract-item/management-tab/management-tab.component.html
- src/app/pages/contracts/contract-item/management-tab/management-tab.component.scss
- src/app/shared/components/charts/gantt-chart/gantt-chart.component.ts
- src/app/shared/components/charts/gantt-chart/gantt-renderers.ts
- src/app/shared/components/charts/gantt-chart/task-data-manipulator.ts
Exemplo com nenhum item/ação
Exemplo com 1 item/ação
Exemplo com 2 itens/ações
Exemplo com 3 itens/ações
Exemplo com várias itens/ações
> [NWS-1207][NWS-1386] Fix gantt chart bug when it has less than 3 tasks

- backend/src/models/platformConfig.ts
- playground.mongodb
- src/app/@core/core.module.ts
- src/app/@theme/components/header/config/config-dialog/config-dialog.component.html
- src/app/@theme/components/header/config/config.component.html
- src/app/@theme/components/header/config/config.component.scss
- src/app/@theme/components/header/config/config.component.ts
- src/app/pages/profile/profile.component.ts
- src/app/shared/guards/auth.guard.spec.ts
- src/app/shared/guards/auth.guard.ts
> [NWS-1321][NWS-1363] Handle control access list dynamically

- src/app/@theme/components/header/config/config-dialog/config-dialog.component.html
- src/app/@theme/components/header/config/config-dialog/config-dialog.component.scss
- src/app/@theme/components/header/config/config-dialog/config-dialog.component.ts
- src/app/@theme/components/header/header.component.html
- src/app/@theme/components/header/header.component.scss
- src/app/@theme/components/header/header.component.ts
- src/app/pages/contracts/contract-item/management-tab/management-tab.component.html
- src/app/pages/contracts/contract-item/management-tab/management-tab.component.scss
- src/app/pages/contracts/contract-item/management-tab/management-tab.component.ts
- src/app/shared/services/string-util.service.ts
Comentários após as alterações
Notificações após as alterações
Notificação aberta depois das alterações
Comentários no main atual
Notificações no main atual
Notificação aberta no main atual
> [NWS-1172][NWS-1421] Show mentions as bold in notifications and improve comments styles

- src/index.html
> [NWS-1409][NWS-1411] Replace nortan spinner with akveo default spinner

- backend/src/models/team.ts
- playground.mongodb
- src/app/pages/dashboard/dashboard.component.html
- src/app/pages/dashboard/dashboard.component.ts
- src/app/pages/teams/team-dialog/team-dialog.component.html
- src/app/pages/teams/team-dialog/team-dialog.component.ts
- src/app/shared/services/team.service.ts
Dashboard quando não há um time da organização definido:
Edição do time com novo toggle:
Edição do time com time da organização marcado:
Edição de outro time quando já há um time da organização:
Dashboard quando há um time da organização:
> [NWS-1409][NWS-1415] Remover aba fixa do time Nortan e deixar essa aba para o time que tem o mesmo nome da empresa

- src/app/pages/dashboard/progress-section/progress-section.component.ts
- src/app/shared/services/config.service.ts
- src/app/shared/services/contract.service.ts
- src/app/shared/services/contractor.service.ts
- src/app/shared/services/course.service.ts
- src/app/shared/services/invoice.service.ts
- src/app/shared/services/message.service.ts
- src/app/shared/services/metrics.service.ts
- src/app/shared/services/promotion.service.ts
- src/app/shared/services/prospect.service.ts
- src/app/shared/services/team.service.ts
- src/app/shared/services/transaction.service.ts
- src/app/shared/services/user.service.spec.ts
- src/app/shared/services/user.service.ts
Métricas G4
Métricas Nortan
Métricas na aba do time Nortan
> [NWS-1409][NWS-1412] Improve metrics with data loaded observables

- src/app/pages/contracts/contract-dialog/contract-dialog.component.html
- src/app/pages/contracts/contract-dialog/contract-dialog.component.scss
- src/app/pages/contracts/contract-dialog/contract-dialog.component.ts
Print do botão no header do diálogo
> [NWS-1311][NWS-1313] Add download expenses report button in contract item

- backend/src/models/team.ts
- src/app/pages/invoices/invoice-item/invoice-item.component.ts
- src/app/pages/teams/team-item/team-item.component.html
- src/app/pages/teams/team-item/team-item.component.ts
- src/app/shared/services/metrics.service.ts
- src/app/shared/services/team.service.ts
… adding new sectors in the settings
> [NWS-1409][NWS-1439]  List of sectors for non-members

- src/app/pages/contracts/contract-item/expense-tab/expense-tab.component.ts
- src/app/shared/report-generator.ts
Print da tabela
Tabela gerada em .ods e .csv
[relatorio_despesas.ods](https://github.com/ninc-management/plataforma/files/8712214/relatorio_despesas.ods)
[relatorio_despesas.csv](https://github.com/ninc-management/plataforma/files/8712215/relatorio_despesas.csv)
> [NWS-1311][NWS-1316] Add generate expenses report function

- backend/src/models/platformConfig.ts
- src/app/@theme/components/header/config/config.component.html
- src/app/@theme/components/header/config/config.component.ts
- src/app/pages/invoices/invoice-item/invoice-item.component.ts
- src/app/shared/config-validation.json
Sigla com menos de 2 caracteres
Input de sigla vazio
Sigla com 2 caracteres (ou mais)
Tooltip da sigla
> [NWS-1409][NWS-1448] Invoice code abbreviation is now a invoice configuration

- src/app/shared/components/charts/gantt-chart/date-manipulator.ts
- src/app/shared/components/charts/gantt-chart/gantt-chart.component.ts
- src/app/shared/components/charts/gantt-chart/gantt-renderers.ts
- src/app/shared/components/charts/gantt-chart/task-data-manipulator.ts
Data da task mais cedo sendo posterior ao início do contrato
Data da task mais cedo sendo anterior ao início do contrato
Gráfico mais cheio com data da task mais cedo sendo posterior ao início do contrato
> [NWS-1409][NWS-1458] Improve gantt chart x axis start date

- backend/src/models/platformConfig.ts
- src/app/@theme/components/footer/footer.component.ts
- src/app/@theme/components/header/config/config.component.html
- src/app/@theme/components/header/header.component.ts
Add an input for the company name to social
> [NWS-1409][NWS-1455] Add an input for the company name to social

- src/app/pages/contracts/contract-item/management-tab/management-tab.component.ts
- src/app/pages/dashboard/dashboard.component.html
Fiz no plataforma porque afetava todo mundo
Antes
Depois
> [NWS-1409][NWS-1467] Fix item progress bar

- src/app/pages/pages.component.ts
Tentei tirar o print com a barra lateral expandida mas na hora do print ela volta. Mas aparece o título aparece OK na expandida
> [NWS-1409][NWS-1482] Fix customers icon disappearing

- backend/src/models/platformConfig.ts
- src/app/@theme/components/header/config/config.component.html
- src/app/@theme/components/header/config/config.component.scss
- src/app/pages/pages.component.ts
> [NWS-1409][NWS-1485] Add modules config

- src/app/pages/contracts/contract-item/expense-item/expense-item.component.ts
- src/app/pages/contracts/contract-item/payment-item/payment-item.component.ts
- src/app/pages/contracts/contract-item/receipt-item/receipt-item.component.ts
- src/app/shared/services/notification.service.ts
- src/app/shared/utils.spec.ts
- src/app/shared/utils.ts
> [NWS-1354][NWS-1490] Notify manager when resources in contract are paid

- src/app/pages/contracts/contract-dialog/contract-dialog.component.html
- src/app/pages/contracts/contract-dialog/contract-dialog.component.ts
- src/app/pages/contracts/contract-item/contract-item.component.html
- src/app/pages/contracts/contract-item/contract-item.component.ts
- src/app/pages/contracts/contract-item/data-tab/data-tab.component.ts
- src/app/shared/components/base-dialog/base-dialog.component.ts
Dialogo de confirmação do descarte de alterações:
> [NWS-1351][NWS-1507] Display confirmation dialog to dismiss data from contract data tab

- src/app/pages/contracts/contract-item/contract-item.component.html
- src/app/pages/contracts/contract-item/management-tab/checklist-item-dialog/checklist-item-dialog.component.html
- src/app/pages/contracts/contract-item/management-tab/checklist-item-dialog/checklist-item-dialog.component.ts
- src/app/pages/contracts/contract-item/management-tab/management-tab.component.html
- src/app/pages/contracts/contract-item/management-tab/management-tab.component.ts
Esse branch é com base no NWS-1507
> [NWS-1351][NWS-1516] Display confirmation dialog to dismiss data from contract management tab

- backend/src/models/contract.ts
- src/app/pages/contracts/contract-dialog/contract-dialog.component.html
- src/app/pages/contracts/contract-item/expense-item/expense-item.component.ts
Esse branch é com base no NWS-1516
> [NWS-1351][NWS-1522] Display confirmation dialog to dismiss data from contract expense tab

- src/app/shared/services/metrics.service.ts
> [NWS-840][NWS-849] Add function that returns accumulated value by contractor

- backend/src/models/platformConfig.ts
- src/app/@theme/components/header/config/config.component.html
- src/app/@theme/components/header/config/config.component.ts
- src/app/pages/contracts/contract-item/expense-item/expense-item.component.ts
- src/app/pages/contracts/contract-item/payment-item/payment-item.component.ts
- src/app/pages/contracts/contract-item/receipt-item/receipt-item.component.ts
- src/app/shared/services/notification.service.ts
Receipt/Payment/Expense Order Created
> [NWS-1354][NWS-1489] Receipt/Payment/Expense Order Created

- src/app/pages/invoices/invoice-dialog/invoice-dialog.component.html
- src/app/pages/invoices/invoice-dialog/invoice-dialog.component.ts
- src/app/pages/invoices/invoice-item/invoice-item.component.ts
Dialogo de confirmação em um orçamento alterado:
> [NWS-1351][NWS-1529] Display confirmation dialog to dismiss data from invoice

- src/app/pages/courses/course-dialog/course-dialog.component.html
- src/app/pages/courses/course-dialog/course-dialog.component.ts
- src/app/pages/courses/course-item/course-item.component.ts
> [NWS-1351][NWS-1533] Add dialog to confirm discard changes in course

- src/app/@theme/components/header/header.component.scss
- src/app/pages/promotions/promotion-dialog/promotion-dialog.component.html
- src/app/pages/promotions/promotion-dialog/promotion-dialog.component.ts
- src/app/pages/promotions/promotion-item/promotion-item.component.ts
> [NWS-1351][NWS-1532] Add dialog to confirm discarding changes - PROMOTION

- backend/src/models/platformConfig.ts
- playground.mongodb
- src/app/@theme/components/header/config/config.component.html
- src/app/@theme/components/header/config/config.component.ts
- src/app/shared/components/teams/team-expenses/team-expense-item/team-expense-item.component.spec.ts
- src/app/shared/components/teams/team-expenses/team-expense-item/team-expense-item.component.ts
- src/app/shared/components/teams/team-expenses/team-expenses.component.ts
- src/app/shared/guards/auth.guard.spec.ts
- src/app/shared/services/config.service.spec.ts
- src/app/shared/services/config.service.ts
- src/app/shared/services/storage.service.spec.ts
Create new list of administrative expense types
> [NWS-1224][NWS-1553] Create new list of administrative expense types

- src/app/pages/dashboard/dashboard.component.html
- src/app/pages/dashboard/dashboard.component.ts
- src/app/shared/components/expansive-list/expansive-list.component.html
> [NWS-784][NWS-1535] Add paretto ranking as expansive list in dashboard

- src/app/pages/dashboard/dashboard.component.html
- src/app/pages/dashboard/dashboard.component.ts
- src/app/shared/components/expansive-list/expansive-list.component.html
- src/app/shared/components/expansive-list/expansive-list.component.scss
- src/app/shared/components/expansive-list/expansive-list.component.ts
Quando não tem nada pra mostrar
Quando tá carregando
> [NWS-784][NWS-1554] Add loading spinner and empty items message

- src/app/pages/contracts/contract-item/management-tab/management-tab.component.html
- src/app/shared/migration.ts
> [NWS-1378][NWS-1596] Disable management end date input and add tooltip

- backend/src/models/team.ts
- playground.mongodb
- src/app/pages/profile/profile.component.html
- src/app/pages/teams/team-item/team-item.component.html
- src/app/pages/teams/team-item/team-item.component.ts
- src/app/shared/services/contract.service.spec.ts
- src/app/shared/services/notification.service.spec.ts
- src/app/shared/utils.spec.ts
Ao adicionar
Adicionado
No perfil
> [NWS-1378][NWS-1589] Add multiple sector selection when adding team member

- src/app/pages/contracts/contracts.component.ts
- src/app/pages/users/users.component.scss
- src/app/pages/users/users.component.ts
- src/app/shared/components/selector-dialog/selector-dialog.component.html
- src/app/shared/components/selector-dialog/selector-dialog.component.ts
Parece que o ícone tá em hover sem o mouse estar em cima mas o mouse de fato estava em cima. Por algum motivo meu mouse não sai nos screenshots do PopOS
> [NWS-1378][NWS-1594] Add close icon in report config and selector dialogs

- backend/src/models/platformConfig.ts
- playground.mongodb
- src/app/@theme/components/header/config/config.component.html
> [NWS-1378][NWS-1611] Add company data fields and inputs in social config

- playground.mongodb
A alteração já foi feita via interface no banco de homologação
> [NWS-1378][NWS-1591] Fix specific expense type name in config document

- src/app/shared/components/charts/echarts-bar/echarts-bar.component.ts
> [NWS-1378][NWS-1592] Rotate x axis label in contract expenses chart

- src/app/pages/invoices/pdf.service.ts
PDF do orçamento com e sem as informações definidas nas configurações sociais:
> [NWS-1378][NWS-1633] Use social config to fill invoice pdf informations

- src/app/pages/dashboard/metric-item/metric-item.component.html
- src/app/pages/dashboard/metric-item/metric-item.component.scss
- src/app/pages/dashboard/metric-item/metric-item.component.ts
- src/app/pages/dashboard/progress-section/progress-section.component.ts
> [NWS-1453][NWS-1683] Improve metric item visual and fix metrics data array

- src/app/pages/dashboard/metric-item/metric-item.component.html
- src/app/pages/dashboard/metric-item/metric-item.component.scss
- src/app/pages/dashboard/metric-item/metric-item.component.ts
- src/app/pages/dashboard/progress-section/progress-section.component.ts
> [NWS-1453][NWS-1675] Add receivable contract metric

- src/app/pages/dashboard/metric-item/metric-item.component.html
- src/app/pages/dashboard/metric-item/metric-item.component.scss
- src/app/pages/dashboard/metric-item/metric-item.component.ts
- src/app/pages/dashboard/progress-section/progress-section.component.ts
- src/app/shared/services/contract.service.ts
> [NWS-1453][NWS-1674] Add ongoing contracts metric

- src/app/pages/dashboard/metric-item/metric-item.component.html
- src/app/pages/dashboard/metric-item/metric-item.component.scss
- src/app/pages/dashboard/metric-item/metric-item.component.ts
- src/app/pages/dashboard/progress-section/progress-section.component.ts
- src/app/shared/services/contract.service.ts
- src/app/shared/services/metrics.service.ts
> [NWS-1453][NWS-1673] Add in review invoices metric

- src/app/pages/dashboard/metric-item/metric-item.component.html
- src/app/pages/dashboard/metric-item/metric-item.component.scss
- src/app/pages/dashboard/metric-item/metric-item.component.ts
- src/app/pages/dashboard/progress-section/progress-section.component.ts
- src/app/shared/services/contract.service.ts
- src/app/shared/services/metrics.service.ts
> [NWS-1453][NWS-1672] Adapt expenses average metric to show only average value

- src/app/pages/dashboard/metric-item/metric-item.component.html
- src/app/pages/dashboard/metric-item/metric-item.component.scss
- src/app/pages/dashboard/metric-item/metric-item.component.ts
- src/app/pages/dashboard/progress-section/progress-section.component.ts
- src/app/shared/services/contract.service.ts
- src/app/shared/services/metrics.service.ts
> [NWS-1453][NWS-1665] Add received metric

- src/app/pages/dashboard/metric-item/metric-item.component.html
- src/app/pages/dashboard/metric-item/metric-item.component.scss
- src/app/pages/dashboard/metric-item/metric-item.component.ts
- src/app/pages/dashboard/progress-section/progress-section.component.ts
- src/app/shared/services/contract.service.ts
- src/app/shared/services/metrics.service.ts
> [NWS-1453][NWS-1664] Add user expenses average metric function

- src/app/pages/dashboard/metric-item/metric-item.component.html
- src/app/pages/dashboard/metric-item/metric-item.component.scss
- src/app/pages/dashboard/metric-item/metric-item.component.ts
- src/app/pages/dashboard/progress-section/progress-section.component.ts
- src/app/pages/promotions/promotion-item/promotion-item.component.ts
- src/app/shared/services/contract.service.ts
- src/app/shared/services/metrics.service.ts
> [NWS-1453][NWS-1663] Add user received value average metric

- src/app/pages/dashboard/metric-item/metric-item.component.html
- src/app/pages/dashboard/metric-item/metric-item.component.scss
- src/app/pages/dashboard/metric-item/metric-item.component.ts
- src/app/pages/dashboard/progress-section/progress-section.component.ts
- src/app/pages/promotions/promotion-item/promotion-item.component.ts
- src/app/shared/services/contract.service.ts
- src/app/shared/services/metrics.service.ts
Fazer o merge da NWS-1638 antes do merge dessa
> [NWS-1453][NWS-1640] Add user balance sum in contracts metric

- src/app/pages/invoices/pdf.service.ts
Lista de atividades marcado como visível:
Lista de atividades marcado como invisível:
> [NWS-1471][NWS-1644] Hide items marked as invisible in invoice PDF

- src/app/pages/courses/course-item/course-item.component.html
- src/app/pages/courses/course-item/course-item.component.ts
- src/app/pages/invoices/invoice-item/invoice-item.component.html
- src/app/pages/invoices/pdf.service.ts
- src/app/pages/promotions/promotion-item/promotion-item.component.html
- src/app/shared/services/course.service.spec.ts
- src/app/shared/services/course.service.ts
- src/app/shared/utils.ts
Imagem com o ícone de visibilidade, ativado e desativado, ao lado dos itens de atividade:
> [NWS-1471][NWS-1643]Add eye icon to check if item is visible

- src/app/@theme/components/header/config/config.component.html
> [NWS-1224][NWS-1715] Add new label divider in platform config social tab

- src/app/@theme/components/header/config/config.component.html
> [NWS-1224][NWS-1716] Add divider in platform configuration onedrive tab

- src/app/@theme/components/header/config/config.component.html
- src/app/@theme/components/header/config/config.component.ts
> [NWS-1224][NWS-1714] Make use of outline icons in config tabs

- src/app/pages/invoices/pdf.service.ts
> [NWS-1224][NWS-1707] Change column header to "VALOR UNITÁRIO"

- src/app/pages/invoices/pdf.service.ts
Tabela simples:
Tabela completa:
> [NWS-1224][NWS-1702] Adjust column width to fit larger values

- src/app/pages/contracts/contracts.component.ts
> [NWS-1224][NWS-1794] Make contract status filter selection multiple

- backend/src/models/contractor.ts
- playground.mongodb
- src/app/pages/contractors/contractor-dialog/contractor-dialog.component.html
- src/app/pages/contractors/contractor-dialog/contractor-dialog.component.ts
- src/app/pages/contractors/contractor-item/contractor-item.component.html
- src/app/pages/contractors/contractor-item/contractor-item.component.scss
- src/app/pages/contractors/contractor-item/contractor-item.component.ts
- src/app/pages/contractors/representative-item/representative-item.component.html
- src/app/pages/contractors/representative-item/representative-item.component.spec.ts
- src/app/pages/contractors/representative-item/representative-item.component.ts
- src/app/pages/pages.module.ts
- src/app/shared/services/contractor.service.spec.ts
- src/app/shared/utils.spec.ts
- src/app/shared/validators/contractor-validation.json
> [NWS-531][NWS-1787] Add representatives lists

- src/app/pages/dashboard/dashboard.component.html
> [NWS-1171][NWS-1806] Merge all dashboard FAB menus

- backend/src/models/platformConfig.ts
- playground.mongodb
- src/app/@theme/components/header/config/config.component.html
- src/app/pages/contracts/contract-item/balance-tab/balance-tab.component.ts
- src/app/pages/contracts/contract-item/data-tab/data-tab.component.ts
- src/app/pages/contracts/contract-item/receipt-item/receipt-item.component.ts
- src/app/pages/contracts/contracts.component.ts
- src/app/pages/invoices/invoice-item/invoice-item.component.ts
- src/app/pages/users/users.component.ts
- src/app/shared/services/config.service.ts
- src/app/shared/services/contract.service.spec.ts
- src/app/shared/services/contract.service.ts
- src/app/shared/services/metrics.service.ts
- src/app/shared/utils.spec.ts
- src/app/shared/utils.ts
> [NWS-1224][NWS-1800] Add configuration for intermediation fees

- src/app/pages/promotions/promotion-item/promotion-item.component.ts
Investigate the reason for registering a new message to discard new changes
> [NWS-1224][NWS-1818] Investigate issue registering a new promotion

- src/app/pages/contracts/contracts.component.html
- src/app/pages/contracts/contracts.component.scss
- src/app/pages/contracts/contracts.component.ts
- src/app/pages/dashboard/dashboard.module.ts
- src/app/pages/dashboard/report-menu/ongoing-contracts-report/ongoing-contracts-report.component.html
- src/app/pages/dashboard/report-menu/ongoing-contracts-report/ongoing-contracts-report.component.scss
- src/app/pages/dashboard/report-menu/ongoing-contracts-report/ongoing-contracts-report.component.spec.ts
- src/app/pages/dashboard/report-menu/ongoing-contracts-report/ongoing-contracts-report.component.ts
- src/app/pages/dashboard/report-menu/report-menu.component.html
- src/common-testing.module.ts
> [NWS-1512][NWS-1826] Migrate ongoing contracts report generation

- src/app/pages/contracts/contracts.component.html
- src/app/pages/contracts/contracts.component.scss
- src/app/pages/contracts/contracts.component.ts
- src/app/pages/dashboard/dashboard.component.html
- src/app/pages/dashboard/dashboard.component.ts
- src/app/pages/dashboard/dashboard.module.ts
- src/app/pages/dashboard/report-menu-dialog/report-menu-dialog.component.html
- src/app/pages/dashboard/report-menu/ongoing-contracts-report/ongoing-contracts-report.component.html
- src/app/pages/dashboard/report-menu/ongoing-contracts-report/ongoing-contracts-report.component.scss
- src/app/pages/dashboard/report-menu/ongoing-contracts-report/ongoing-contracts-report.component.spec.ts
- src/app/pages/dashboard/report-menu/ongoing-contracts-report/ongoing-contracts-report.component.ts
- src/app/pages/dashboard/report-menu/report-menu.component.html
- src/app/pages/dashboard/report-menu/report-menu.component.scss
- src/app/pages/dashboard/report-menu/report-menu.component.spec.ts
- src/app/pages/dashboard/report-menu/report-menu.component.ts
- src/common-testing.module.ts
> [NWS-1512][NWS-1810] Add initial report generation menu as a stepper

- backend/src/app.ts
Pensei em deixar os consoles pra que eles apareçam nos logs de produção caso ocorra algum problema novamente
> [NWS-1445][NWS-1843] Fix disconnected database crashing application

- src/app/pages/contracts/contract-dialog/contract-dialog.component.html
- src/app/pages/contracts/contract-dialog/contract-dialog.component.ts
- src/app/pages/dashboard/dashboard.module.ts
- src/app/pages/dashboard/report-menu/contract-expenses-report/contract-expenses-report.component.html
- src/app/pages/dashboard/report-menu/contract-expenses-report/contract-expenses-report.component.scss
- src/app/pages/dashboard/report-menu/contract-expenses-report/contract-expenses-report.component.spec.ts
- src/app/pages/dashboard/report-menu/contract-expenses-report/contract-expenses-report.component.ts
- src/app/pages/dashboard/report-menu/report-menu.component.html
> [NWS-1512][NWS-1828] Migrate contract expenses report generation

- backend/src/models/contract.ts
- backend/src/models/team.ts
- src/app/pages/contracts/contract-item/expense-item/expense-item.component.html
- src/app/pages/contracts/contract-item/expense-item/expense-item.component.ts
- src/app/shared/components/base-expense/base-expense.component.ts
- src/app/shared/components/teams/team-expenses/team-expense-item/team-expense-item.component.html
- src/app/shared/components/teams/team-expenses/team-expense-item/team-expense-item.component.spec.ts
- src/app/shared/components/teams/team-expenses/team-expense-item/team-expense-item.component.ts
Despesa de contrato:
Despesa de time:
> [NWS-1156][NWS-1835] Add provider field to expenses

- backend/src/models/invoice.ts
- backend/src/models/platformConfig.ts
- backend/src/models/provider.ts
- playground.mongodb
- src/app/@theme/components/header/config/config.component.html
- src/app/pages/invoices/invoice-item/invoice-item.component.html
- src/app/pages/invoices/invoice-item/invoice-item.component.ts
- src/app/pages/invoices/pdf.service.ts
- src/app/pages/providers/provider-item/provider-item/provider-item.component.html
- src/app/shared/services/provider.service.ts
- src/app/shared/validators/provider-validation.json
Campo para adicionar fornecedor no orçamento:
Visualização do fornecedor no pdf do orçamento:
> [NWS-1156][NWS-1836] Add provider information to invoice

- backend/src/models/contract.ts
- playground.mongodb
- src/app/pages/contracts/contract-item/balance-tab/balance-tab.component.ts
- src/app/pages/contracts/contract-item/data-tab/data-tab.component.html
- src/app/pages/contracts/contract-item/data-tab/data-tab.component.ts
- src/app/pages/contracts/contract-item/receipt-item/receipt-item.component.html
- src/app/pages/contracts/contract-item/receipt-item/receipt-item.component.ts
- src/app/pages/dashboard/report-menu/annual-users-report/annual-users-report.component.ts
- src/app/shared/services/contract.service.ts
> [NWS-1863][NWS-1872] Move ISS logic to receipts

- src/app/@theme/components/smart-table/components/filter/filter-types/date-filter.component.ts
- src/app/pages/contracts/contracts.component.ts
- src/app/pages/invoices/invoices.component.ts
> [NWS-1875][NWS-1892] Add date column and filter in contract and invoice tables

- src/app/pages/contracts/contract-item/expense-tab/expense-tab.component.ts
- src/app/pages/contracts/contracts.component.ts
- src/app/pages/invoices/invoices.component.ts
> [NWS-1876][NWS-1899] Add value filter for contracts, expenses and invoices tables

- backend/src/models/platformConfig.ts
- backend/src/routes/platformConfig.ts
- playground.mongodb
- src/app/@theme/components/header/config/config-dialog/config-dialog.component.ts
- src/app/@theme/components/header/config/config.component.html
- src/app/@theme/components/header/config/config.component.scss
- src/app/@theme/components/header/config/config.component.ts
- src/app/@theme/components/header/header.component.ts
- src/app/shared/services/config.service.ts
> [NWS-1865][NWS-1895] Add custom colors

- backend/src/models/platformConfig.ts
- playground.mongodb
- src/app/@theme/components/header/config/config.component.html
- src/app/@theme/components/header/config/config.component.ts
- src/app/@theme/theme.module.ts
- src/app/pages/invoices/pdf.service.ts
Exemplo de PDF: [ORC-40_2022-TNT_NINC (18).pdf](https://github.com/ninc-management/plataforma/files/9910353/ORC-40_2022-TNT_NINC.18.pdf)
Exemplo atualizado: [ORC-40_2022-TNT_NINC (18).pdf](https://github.com/ninc-management/plataforma/files/9973389/ORC-40_2022-TNT_NINC.18.pdf)
Configurações na aba de orçamento
> [NWS-1866][NWS-1913] Make invoice pdf reactive to configs

- backend/src/routes/invoice.ts
- backend/src/shared/global.ts
- backend/src/shared/util.ts
> [NINC-1902][NINC-1980] Make connection map and helper function that given a company ID returns or creates a connection

- src/app/pages/contractors/contractors.component.ts
- src/app/pages/teams/teams.component.ts
> [ninc-2021][ninc-2059] Add corporateName and legalRepresentatives column in contractor table

- src/app/pages/users/users.component.scss
> [NINC-2021][NINC-2053] Adjust width of the list of users in the mobile version

- backend/src/routes/notification.ts
- backend/src/routes/user.ts
- src/app/@theme/components/header/header.component.html
- src/app/@theme/components/header/header.component.ts
- src/app/shared/services/notification.service.ts
- src/app/shared/services/user.service.ts
> [ninc-2021][ninc-2061]  Add a button to mark all notifications as read 

- backend/src/routes/contract.ts
- Block saving/updating data from old version of object for contract route
> [NINC-2096][NINC-2109] Feat: add to contract route

- backend/src/models/invoice.ts
- src/app/pages/invoices/invoice-item/invoice-item.component.html
- src/app/pages/invoices/invoice-item/invoice-item.component.ts
Interface desktop
Interface mobile:
> [NINC-719][NINC-2144] Added new field Quantity Parcels in Invoice

- src/app/pages/invoices/invoice-item/invoice-item.component.html
- src/app/pages/invoices/invoice-item/invoice-item.component.ts
> [NINC-719][NINC-2146] Enable number of parcels only if payment type is in parcel

- backend/src/models/invoice.ts
- src/app/pages/invoices/invoice-item/invoice-item.component.html
- src/app/pages/invoices/invoice-item/invoice-item.component.ts
> [NINC-719][NINC-2147] Repositioning parcels quantity interface element

- backend/src/models/invoice.ts
- database/next.mongodb
- src/app/pages/invoices/invoice-item/invoice-item.component.ts
- src/app/shared/mocked-data/mocked-invoices.ts
- src/app/shared/services/invoice.service.ts
Defined default value on Invoice.paymentForm
> [NINC-719][NINC-2149]

- src/app/@theme/components/header/config/config-dialog/config-dialog.component.spec.ts
- src/app/@theme/components/header/config/config.component.spec.ts
- src/app/pages/contracts/contract-dialog/contract-dialog.component.spec.ts
- src/app/pages/contracts/contract-item/balance-tab/balance-tab.component.spec.ts
- src/app/pages/contracts/contract-item/contract-item.component.spec.ts
- src/app/pages/invoices/invoice-dialog/invoice-dialog.component.spec.ts
> [NINC-1897][NINC-2142] Updated test files with registerIcons

- src/app/pages/invoices/invoice-item/invoice-item.component.html
- src/app/pages/invoices/invoice-item/invoice-item.component.ts
> [NINC-719][NINC-2152] Add description of the parcel value

- src/app/pages/invoices/invoice-item/invoice-item.component.html
- src/app/pages/invoices/invoice-item/invoice-item.component.scss
> [NINC-719][NINC-2151] - Limited parcels field to one element and disable fields

- src/app/pages/dashboard/dashboard.component.html
- src/app/pages/dashboard/dashboard.component.ts
- src/app/shared/components/expansive-list/expansive-list.component.html
- src/app/shared/components/expansive-list/expansive-list.component.scss
> [NINC-783][NINC-2153] Create component in the dashboard

- src/app/public/contractor-edit/contractor-edit.component.html
- src/app/public/contractor-edit/contractor-edit.component.spec.ts
- src/app/public/contractor-edit/contractor-edit.component.ts
- src/app/public/public-routing.module.ts
> [NINC-2054][NINC-2163] Created edit client public route

- src/app/public/contractor-edit/contractor-edit.component.html
- src/app/public/contractor-edit/contractor-edit.component.spec.ts
- src/app/public/contractor-edit/contractor-edit.component.ts
- src/app/public/public-routing.module.ts
- src/app/public/public.module.ts
Co-authored-by: Ayrton O. Ouriques <kharon404@outlook.com>
> [NINC-2054][NINC-2162] - Created a new component empty to  public client edit

- src/app/pages/dashboard/dashboard.component.ts
- src/app/shared/services/contract.service.ts
> [NINC-783][NINC-2155] Create function to return open OPs

- src/app/pages/dashboard/dashboard.component.html
- src/app/pages/dashboard/dashboard.component.ts
- src/app/shared/components/expansive-list/expansive-list.component.html
- src/app/shared/components/expansive-list/expansive-list.component.spec.ts
- src/app/shared/components/expansive-list/expansive-list.component.ts
- src/app/shared/services/contract.service.ts
Co-authored-by: Pâmela Medeiros  <pms2@ic.ufal.br>
> [NINC-783][NINC-2160] Open contract dialog when click on a item of Open OPs list

- src/app/pages/contractors/contractors.module.ts
- src/app/pages/pages.module.ts
- src/app/public/contractor-edit/contractor-edit.component.html
- src/app/public/contractor-edit/contractor-edit.component.scss
- src/app/public/contractor-edit/contractor-edit.component.ts
- src/app/public/public.component.html
- src/app/public/public.component.ts
- src/app/public/public.module.ts
- src/common-testing.module.ts
> [NINC-2054][NINC-2164] - Created route public to edit contractors and fix bug in public pages

- src/app/pages/dashboard/dashboard.component.ts
> [NINC-783][NINC-2154] Open OP directly in a

- src/app/pages/contractors/contractor-item/contractor-item.component.ts
> [NINC-2054][NINC-2171] Fixed CNPJ/CPF edit bug in Contractor

- src/app/pages/contracts/contract-item/data-tab/data-tab.component.ts
- src/app/pages/invoices/invoice-item/invoice-item.component.ts
> [NINC-2167][NINC-2173] Fix contract author not being shown in contract

- src/app/pages/contractors/contractor-dialog/contractor-dialog.component.html
- src/app/pages/contractors/contractor-dialog/contractor-dialog.component.ts
- src/app/shared/directives/copy-clipboard.directive.ts
- src/app/shared/shared.module.ts
> [NINC-2054][NINC-2165] Created link generator button on contractor edit

- src/app/pages/contracts/contract-dialog/contract-dialog.component.html
- src/app/pages/contracts/contract-dialog/contract-dialog.component.scss
- src/app/pages/contracts/contract-dialog/contract-dialog.component.ts
Co-authored-by: MattRamm4 <124637182+MattRamm4@users.noreply.github.com>
> [NINC-2137][NINC-2180] Created spinner while button is deactivated

- src/app/pages/contracts/contract-dialog/contract-dialog.component.html
- src/app/pages/contracts/contract-dialog/contract-dialog.component.scss
- src/app/pages/contracts/contract-dialog/contract-dialog.component.ts
Co-authored-by: MattRamm4 <124637182+MattRamm4@users.noreply.github.com>
> [NINC-2137][NINC-2179] Disabilitated create one driver folder button on click

- src/app/pages/dashboard/dashboard.component.html
> [NINC-77][NINC-2176] Create card in the Nortan tab with the Nortan calendar.

- backend/src/routes/contractor.ts
- src/app/pages/contractors/contractor-dialog/contractor-dialog.component.html
- src/app/pages/contractors/contractor-dialog/contractor-dialog.component.ts
- src/app/shared/utils.ts
> [NINC-1153][NINC-2182] Implement visual feedback to outdated Contractor object

- backend/src/routes/provider.ts
- src/app/pages/providers/provider-dialog/provider-dialog/provider-dialog.component.html
- src/app/pages/providers/provider-dialog/provider-dialog/provider-dialog.component.ts
> [NINC-1153][NINC-2184] Created visual feedback on provider dialog

- backend/src/routes/user.ts
- src/app/pages/profile/profile.component.ts
- src/app/pages/users/user-dialog/user-dialog.component.html
- src/app/pages/users/user-dialog/user-dialog.component.ts
> [NINC-1153][NINC-2186] Implement visual feedback to outdated User object

- src/app/pages/contractors/contractor-dialog/contractor-dialog.component.html
- src/app/pages/invoices/invoice-dialog/invoice-dialog.component.html
- src/app/pages/invoices/invoice-dialog/invoice-dialog.component.ts
- src/app/pages/invoices/invoice-item/invoice-item.component.ts
> [NINC-1153][NINC-2187] Implement visual feedback to outdated Invoice object

- backend/src/routes/course.ts
- src/app/pages/courses/course-dialog/course-dialog.component.html
- src/app/pages/courses/course-dialog/course-dialog.component.ts
- src/app/pages/providers/provider-dialog/provider-dialog/provider-dialog.component.ts
> [NINC-1153][NINC-2189] Implement visual feedback to outdated Course object

- backend/src/routes/team.ts
- src/app/pages/teams/team-dialog/team-dialog.component.html
- src/app/pages/teams/team-dialog/team-dialog.component.scss
- src/app/pages/teams/team-dialog/team-dialog.component.ts
> [NINC-1153][NINC-2185] Implement visual feedback to outdated Team object

- src/app/pages/dashboard/dashboard.component.html
> [NINC-2190][NINC-2193] Replace Google Calendar to Styled Calendar in Dashboard

- src/app/pages/contracts/contract-dialog/contract-dialog.component.html
- src/app/pages/contracts/contract-dialog/contract-dialog.component.scss
- src/app/pages/contracts/contract-dialog/contract-dialog.component.ts
- src/app/pages/contracts/contract-item/contract-item.component.ts
- src/app/pages/invoices/invoice-dialog/invoice-dialog.component.html
- src/app/pages/invoices/invoice-dialog/invoice-dialog.component.scss
- src/app/pages/invoices/invoice-dialog/invoice-dialog.component.ts
- src/app/shared/services/contract.service.ts
> [NINC-1153][NINC-2188] Implement visual feedback to outdated Contract object

- src/app/pages/dashboard/dashboard.component.html
> [NINC-2207][NINC-2214] Create component with empty list in the dashboard

- src/app/@theme/components/smart-table/components/tbody/cells/edit-delete.component.ts
- src/app/pages/contracts/contracts.component.scss
- src/app/pages/contracts/contracts.component.ts
> [NINC-1151][NINC-2196] Differentiate contracts with cash in the contracts list

- src/app/pages/dashboard/dashboard.component.html
- src/app/pages/dashboard/dashboard.component.ts
- src/app/shared/services/contract.service.ts
> [NINC-2207][NINC-2215] Populate list with open contract receipts

- src/app/pages/dashboard/dashboard.component.html
- src/app/pages/dashboard/dashboard.component.ts
> [NINC-2207][NINC-2216] Open receipt dialog by clicking on an item of the list

- angular.json
- src/app/@theme/layouts/one-column/one-column.layout.ts
- src/app/pages/dashboard/dashboard.component.ts
- src/app/pages/pages.component.html
- src/app/pages/pages.component.ts
- src/app/shared/services/app-updater.service.ts
- src/index.html
- src/manifest.webmanifest
> [NINC-1935][NINC-2203] Added PWA install button on sidebar

- src/app/@theme/theme.module.ts
- src/app/pages/dashboard/dashboard.component.html
- src/app/pages/dashboard/dashboard.component.ts
> [NINC-2190][NINC-2194] Create Calendar Light version and Implements change Theme color

- src/app/pages/dashboard/dashboard.component.html
- src/app/pages/dashboard/dashboard.component.ts
- src/app/shared/components/expansive-list/expansive-list.component.html
- src/app/shared/components/expansive-list/expansive-list.component.ts
- src/app/shared/services/contract.service.ts
> [NINC-2208][NINC-2211] Populate list with open contract expenses

- src/app/pages/contracts/contract-item/receipt-item/receipt-item.component.html
- src/app/pages/contracts/contracts.component.html
- src/app/pages/contracts/contracts.component.ts
> [NINC-2029][NINC-2221] Save filtered OEs to .csv

- src/app/pages/contracts/contracts.component.ts
> [NINC-2029][NINC-2222] Save filtered OPs to .csv

- src/app/pages/contracts/contracts.component.ts
> [NINC-2029][NINC-2220] Save filtered contracts to .csv

- src/app/pages/contracts/contract-item/receipt-item/receipt-item.component.html
- src/app/pages/contracts/contracts.component.html
- src/app/pages/contracts/contracts.component.scss
- src/app/pages/contracts/contracts.component.ts
> [NINC-2029][NINC-2219] Create button to download contract csv files

- src/app/pages/contracts/contracts.component.html
> [NINC-1920][NINC-2229] Add an empty Gantt chart to the timeline tab

- src/app/pages/contracts/contracts.component.html
- src/app/pages/contracts/contracts.component.scss
- src/app/pages/contracts/contracts.component.ts
> [NINC-1920][NINC-2227] Create contract view tabs

- src/app/pages/dashboard/dashboard.component.html
- src/app/pages/dashboard/dashboard.component.scss
- src/app/pages/dashboard/dashboard.component.ts
> [NINC-785][NINC-2239] Created announcements tab on dashboard

- backend/src/models/company.ts
- src/app/pages/dashboard/dashboard.component.html
- src/app/pages/dashboard/dashboard.component.scss
- src/app/pages/dashboard/dashboard.component.ts
- src/app/pages/dashboard/dashboard.module.ts
- src/app/shared/components/text-input-dialog/text-input-dialog.component.html
- src/app/shared/components/text-input-dialog/text-input-dialog.component.ts
- src/app/shared/mocked-data/mocked-companies.ts
- src/app/shared/shared.module.ts
> [NINC-785][NINC-2238] Finished tinymce integration with announcements tab and adapted textinputdialog component

- src/app/pages/contracts/contracts.component.ts
- src/app/shared/components/charts/gantt-chart/gantt-chart.component.ts
- src/app/shared/components/charts/gantt-chart/gantt-renderers.ts
- src/app/shared/components/charts/gantt-chart/task-data-manipulator.ts
- src/app/shared/components/charts/gantt-chart/task-data.model.ts
> [NINC-1920][NINC-2251] Display contract status

- src/app/pages/contracts/contracts.component.ts
- src/app/shared/components/charts/gantt-chart/gantt-chart.component.ts
- src/app/shared/components/charts/gantt-chart/gantt-renderers.ts
- src/app/shared/components/charts/gantt-chart/task-data-manipulator.ts
- src/app/shared/components/charts/gantt-chart/task-data.model.ts
> [NINC-1920][NINC-2250] Adjustment of end date for contracts with status 'Entregue' or 'Arquivado'.

- src/app/pages/contracts/contracts.component.html
- src/app/pages/contracts/contracts.component.ts
- src/app/shared/components/charts/gantt-chart/gantt-chart.component.ts
- src/app/shared/components/charts/gantt-chart/gantt-renderers.ts
- src/app/shared/components/charts/gantt-chart/task-data-manipulator.ts
- src/app/shared/components/charts/gantt-chart/task-data.model.ts
> [NINC-1920][NINC-2231] Open contract by clicking on an item of the chart

- src/app/pages/contracts/contract-item/management-tab/management-tab.component.ts
- src/app/pages/contracts/contracts.component.html
- src/app/pages/contracts/contracts.component.ts
- src/app/shared/components/charts/gantt-chart/gantt-chart.component.ts
- src/app/shared/components/charts/gantt-chart/gantt-renderers.ts
- src/app/shared/components/charts/gantt-chart/task-data-manipulator.ts
- src/app/shared/components/charts/gantt-chart/task-data.model.ts
> [NINC-1920][NINC-2230] Populate gantt chart with filtered contracts data

- src/app/pages/dashboard/dashboard.component.html
- src/app/pages/dashboard/dashboard.component.scss
- src/app/pages/dashboard/dashboard.component.ts
- src/app/shared/services/metrics.service.ts
> [NINC-2252][NINC-2257] Fix dashboard's chart bug

- src/app/pages/invoices/invoice-item/invoice-item.component.html
> [NINC-554][NINC-2260] - Fixed graphical bugs on invoice complement values table

- src/app/pages/contracts/contract-item/balance-tab/balance-tab.component.scss
- src/app/pages/contracts/contract-item/contract-item.component.scss
- src/app/pages/contracts/contract-item/data-tab/data-tab.component.html
- src/app/pages/contracts/contract-item/data-tab/data-tab.component.scss
- src/app/pages/contracts/contract-item/expense-tab/expense-tab.component.scss
- src/app/pages/contracts/contract-item/payment-item/payment-item.component.html
- src/app/pages/contracts/contract-item/payment-item/payment-item.component.scss
- src/app/pages/contracts/contract-item/payment-item/payment-item.component.ts
- src/app/pages/contracts/contract-item/payment-tab/payment-tab.component.html
- src/app/pages/contracts/contract-item/payment-tab/payment-tab.component.scss
- src/app/pages/contracts/contract-item/receipt-tab/receipt-tab.component.scss
- src/app/shared/components/base-expense/base-expense.component.scss
> [NINC-516][NINC-2266] - Fixed payment item graphical errors and removed useless segment in irow css class

- src/app/@theme/styles/_overrides.scss
- src/app/pages/contracts/contract-item/contract-item.component.html
> [NINC-516][NINC-2262] Tabset width should not overflow tab width, add scrollbar

- src/app/pages/contracts/contract-item/balance-tab/balance-tab.component.html
- src/app/pages/contracts/contract-item/balance-tab/balance-tab.component.scss
> [NINC-516][NINC-2264] Table in balance tab should not lose formatting

- src/app/pages/dashboard/charts/gauge/gauge.component.ts
- src/app/pages/dashboard/dashboard.component.html
- src/app/pages/dashboard/dashboard.component.ts
> [NINC-595][NINC-2282] - Created another gauge for measuring OEs.

- src/app/pages/contracts/contract-item/expense-tab/expense-tab.component.html
- src/app/pages/contracts/contract-item/expense-tab/expense-tab.component.scss
> [NINC-516][NINC-2267] Fixed expenses tab css on mobile

- src/app/pages/contracts/contract-item/management-tab/management-tab.component.html
> [NINC-516][NINC-2268] Fixed css and removed graphics tabset on management tab in mobile in the contracts

- src/app/pages/contractors/contractor-item/contractor-item.component.html
- src/app/pages/dashboard/dashboard.component.html
- src/app/pages/dashboard/dashboard.component.ts
- src/app/shared/components/expansive-list/expansive-list.component.html
- src/app/shared/components/expansive-list/expansive-list.component.ts
- src/app/shared/services/contractor.service.spec.ts
- src/app/shared/services/contractor.service.ts
- src/app/shared/utils.ts
> [NINC-2278][NINC-2300] Created new card in dashboard to display the current month birthdays

- src/app/pages/contractors/contractor-item/contractor-item.component.html
- src/app/pages/contractors/contractor-item/contractor-item.component.ts
- src/app/pages/dashboard/dashboard.component.html
- src/app/pages/dashboard/dashboard.component.ts
- src/app/shared/components/expansive-list/expansive-list.component.html
- src/app/shared/components/expansive-list/expansive-list.component.ts
- src/app/shared/services/contractor.service.spec.ts
- src/app/shared/services/contractor.service.ts
- src/app/shared/utils.ts
- src/app/shared/validators/contractor-validation.json
> [NINC-2278][NINC-2299] Created new input for birthday when creating new contractor

- src/app/pages/dashboard/dashboard.component.html
> [NINC-2278][NINC-2310] Changed birthday card from personal tab to company tab

- src/app/pages/dashboard/dashboard.component.html
> [NINC-595][NINC-2314] Added a count number of the amount of open OEs, OPs and Despesas in the dashboard

- src/app/@theme/components/header/config/config.component.html
- src/app/@theme/components/header/config/config.component.ts
- src/app/shared/utils.ts
> [NINC-2305][NINC-2313] Added frontend integration to changes in platform config permissions

- src/app/@theme/components/header/config/config.component.html
- src/app/@theme/components/header/config/config.component.ts
> [NINC-595][NINC-2328] Prevented changing the name of a position when that positions is being used
